[adguard]
adguard.lan ansible_host=192.168.1.53 ansible_user=root

[neon]
neon.lan ansible_host=192.168.1.60 ansible_user=root

[proxmox]
proxmox.lan ansible_host=192.168.1.32 ansible_user=root

[homelab:children]
adguard
neon
proxmox
