[adguard]
adguard.lan ansible_host=192.168.1.53 ansible_user=root

[neon]
neon.lan ansible_host=192.168.1.60 ansible_user=root

[bromine]
bromine.lan ansible_host=192.168.1.61 ansible_user=root

[proxmox]
proxmox.lan ansible_host=192.168.1.32 ansible_user=root

[pbs]
pbs.lan ansible_host=192.168.1.62 ansible_user=root

[immich]
immich.lan ansible_host=192.168.1.63 ansible_user=root

[backup]
backup.lan ansible_host=192.168.1.64 ansible_user=root

[homelab:children]
adguard
neon
bromine
proxmox
pbs
immich
backup
